node.name: "syncday-node-1"
cluster.name: "syncday-cluster"
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node
bootstrap.memory_lock: true
xpack.security.enabled: false
index.number_of_shards: 1
index.number_of_replicas: 0
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs