server:
  port: 5000

spring:
  profiles:
    active: syncday




springdoc:
  swagger-ui:
    # swagger-ui ?? ??. default ?? /swagger-ui.html??.
    path: /swagger-custom-ui.html

    # ? API? ?? ?? ??
    # path, query, body, response ??? ??
    groups-order: DESC

    # ?? ?? ??.
    # alpha: ??? ? ??
    # method: OpenAPI specification file? ??? ?? ?? ?? ?? ??
    tags-sorter: alpha

    # ???? ?? ??.
    # method? delete - get - patch - post - put ??? ????.
    # alpha? ??? ??? ??? ??? ? ??.
    operations-sorter: method

    # swagger-ui default url? petstore html? ???? ??
    disable-swagger-default-url: true

    # swagger-ui?? try ?? ? request duration? ???? ??
    display-request-duration: true

  # Spring Actuator? endpoint?? ??? ????
  show-actuator: true

  # request media type ? ?? ?
  default-consumes-media-type: application/json

  # response media type ? ?? ?
  default-produces-media-type: application/json